In [16]:
import numpy as np
import pandas as pd

df = '../datasets/ecommerce/products.csv'
prices = np.genfromtxt(df, delimiter=',', skip_header=1,usecols=3)
stocks = np.genfromtxt(df, delimiter=',', skip_header=1, usecols=4)

def green_mean():
    """建立 [10, 20, 30, 40, 50]，回傳所有元素的平均值 (float)"""
    # TODO: 你的程式碼
    arr = np.array([10, 20, 30, 40, 50])
    return arr.mean()


print(green_mean())

30.0


In [17]:
def green_double():
    """建立 [10, 20, 30, 40, 50]，回傳所有元素乘以 2 的 ndarray"""
    # TODO: 你的程式碼
    arr = np.array([10, 20, 30, 40, 50])
    return arr * 2

print(green_double())


[ 20  40  60  80 100]


In [18]:
def green_filter():
    """建立 [10, 20, 30, 40, 50]，回傳大於 25 的元素 (ndarray)"""
    # TODO: 你的程式碼
    arr = np.array([10, 20, 30, 40, 50])
    mask = arr > 25
    return arr[mask]

print(green_filter())

[30 40 50]


In [19]:

def yellow_expensive_count(prices):
    """回傳單價 > 1000 的商品數量 (int)"""
    # TODO: 你的程式碼
    mask = prices > 1000
    return int(mask.sum())
print(yellow_expensive_count(prices))

16


In [20]:
def yellow_top3_stock_indices(stocks):
    """
    回傳庫存最多的前 3 個商品的索引位置 (ndarray, 由大到小排)
    提示：np.argsort
    """
    # TODO: 你的程式碼
    stocks2 = np.argsort(stocks)# 這部分說的是按照庫存排序 並返回的是 index值不是排序的數值 
    return stocks2[::-1][:3]


print(yellow_top3_stock_indices(stocks))

[7 8 3]


In [30]:
def yellow_restock_cost(prices, stocks):
    """
    單價 < 500 的商品，每種各進貨 50 個，回傳總花費 (float/int)
    提示：布林遮罩 + .sum()
    """
    # TODO: 你的程式碼
    prices_mask = prices < 500
    cheap_prices = prices[prices_mask]           
    
    cheap_prices_stocks = cheap_prices * 50

    total_cheap_prices_stocks = cheap_prices_stocks.sum()
   
    return total_cheap_prices_stocks
    
print(yellow_restock_cost(prices, stocks))

    

120300.0


In [ ]:
def red_double11_prices(prices, stocks):
    """
    雙 11 定價規則（必須向量化，不能用 for-loop）：
    - 庫存 >= 100：打 7 折
    - 庫存 20~99：打 9 折
    - 庫存 < 20：原價
    回傳每個商品的雙 11 售價 (ndarray)
    提示：np.where 可以巢狀使用
    """
    # TODO: 你的程式碼
    prices_11 = np.where(stocks >= 100, prices * 0.7, 
                         np.where((stocks >= 20) & (stocks <=99), prices*0.9, prices))
    return prices_11

    

In [48]:
DATA = '../datasets/ecommerce/orders_raw.csv'

df = pd.read_csv(DATA)

In [49]:
def green_read_csv():
    """
    讀取 orders_raw.csv，回傳原始 DataFrame（不做任何清理）
    提示：pd.read_csv()
    """
    # TODO: 你的程式碼
    ras = pd.read_csv('datasets/ecommerce/orders_raw.csv')
    
    return ras

In [ ]:
def green_dtypes(df):
    """
    回傳 DataFrame 的欄位型別 (Series)
    提示：df.dtypes
    """
    # TODO: 你的程式碼
    return df.dtypes

In [ ]:
def yellow_clean_amount(df):
    """
    清理 amount 欄位：移除 '$' 和 ',' 符號，轉為 float
    假設欄位名稱已經是小寫的 'amount'
    回傳清理後的 DataFrame（不要修改原始 df）
    提示：.str.replace() + .astype(float)
    """
    # TODO: 你的程式碼
    pass

In [ ]:
def yellow_clean_amount(df):
    """
    清理 amount 欄位：移除 '$' 和 ',' 符號，轉為 float
    假設欄位名稱已經是小寫的 'amount'
    回傳清理後的 DataFrame（不要修改原始 df）
    提示：.str.replace() + .astype(float)
    """
    # TODO: 你的程式碼
    new_df = df.copy()
    new_df['amount'] = new_df['amount'].astype(str).str.replace('$', '', regex=False)
    new_df['amount'] = new_df['amount'].astype(str).str.replace(',', '', regex=False).astype(float)

    return new_df

In [54]:
def yellow_drop_duplicates(df):
    """
    移除完全重複的列，回傳去重後的 DataFrame
    提示：df.drop_duplicates()
    """
    # TODO: 你的程式碼
    new_df = df.copy()
    new_df = new_df.drop_duplicates()
    
    return new_df

In [ ]:

def red_clean_orders(path):
    df = pd.read_csv(path)
    new_df = df.copy()
    new_df.columns = new_df.columns.str.strip().str.lower()
    new_df['amount'] = new_df['amount'].astype(str).str.replace('$','',regex=False)
    new_df['amount'] = new_df['amount'].astype(str).str.replace(',','',regex=False).astype(float)
    new_df['order_date'] = pd.to_datetime(new_df['order_date'],errors='coerce')
    new_df = new_df.dropna(subset= ['order_date'])
    new_df = new_df.dropna(subset= ['amount'])
    new_df = new_df.drop_duplicates()
    return new_df